
-- 文件名称：ChineseConvert.lua
-- 功能描述：中文统一存放,调用使用前面的英文key
-- 文件说明：
-- 作    者：王雷雷
-- 创建时间：2015-5-13
--  修改：TODO:由外部jason文件或txt文件生成，方便策划自己修改
-- 

ChineseConvert = 
{
    --战斗UI
    ["Utility_Country_Wei"] = "魏",
    ["Utility_Country_Shu"] = "蜀",
    ["Utility_Country_Wu"] = "吴",
    ["Utility_HuangJin"] = "黄巾",
    ["Utility_ManZu"] = "蛮族",
    ["UIBattleText_Round"] = "第%d回合",
    ["UIBattleText_TestArmy"]= "数量：%d",
    ["UIBattleText_TestArmyType"] = "种类:%d",
    ["UISoldierText_TiShengValue"] = "%d+%d",
    ["UISoldierText_YuanCheng"] ="远程",
    ["UISoldierText_FangYu"]  = "防御",
    ["UISoldierText_GongJi"] = "攻击",
    ["UISoldierText_DanTi"] = "单体",
    ["UISoldierText_QunTi"] = "群体",
    ["SoldierType_Max"] = "巨大",
    ["UITrainText_ShengYuTuFei"] = "%d",
    ["UITrainText_Time"] = "%02d:%02d:%02d",
    ["UITechnologyText1"] = "等级达到%d级可研究",
    ["UITechnologyText2"] = "通关%s可研究",
    ["UIVipText"] = "包含V%d特权",
    ["ItemName_1"] = "元宝",
    ["ItemName_2"] = "铜钱",
    ["ItemName_3"] = "经验",
    ["ItemName_4"] = "荣誉",
    ["ItemName_5"] = "招募值",
    ["ItemName_6"] = "军令",
    ["UITitle_1"] = "信息",
    ["UITitle_2"] = "进阶",
    ["UITitle_3"] = "进阶成功",
    ["UITitle_4"] = "免费刷新一次",
    ["UITitle_5"] = "已领取",
    ["UITitle_6"] = "合成失败",
    ["UITitle_7"] = "未上榜",
    ["UITitle_8"] = "购买成功",
    ["UITitle_9"] = "转生成功",
    ["UITitle_10"] = "VIP3 可开启",
    ["UITitle_11"] = "打  开",
    ["UITitle_12"] = "卖  出",
    ["UITitle_13"] = "合  成",
    ["UITitle_14"] = "阵型一",
    ["UITitle_15"] = "阵型二",
    ["UITitle_16"] = "阵型三",
    ["UIEquip_2"] = "武器",
    ["UIEquip_4"] = "头盔",
    ["UIEquip_5"] = "胸甲",
    ["UIEquip_3"] = "护腕",
    ["UIEquip_6"] = "鞋子",
    ["UIEquip_7"] = "披风",
    ["UISoldierTip_1"] = "名称",
    ["UISoldierTip_2"] = "士兵类型",
    ["UISoldierTip_3"] = "攻击类型",
    ["UISoldierTip_4"] = "血量",
    ["UISoldierTip_5"] = "攻击",
    ["UISoldierTip_6"] = "攻速",
    ["UISoldierTip_7"] = "攻击距离",
    ["UISoldierTip_8"] = "移动速度",
    ["UISoldierTip_9"] = "消耗",
    ["UISoldierTip_10"] = "产出",
    ["UISoldierTip_11"] = "人口",
    ["UIShaChangJiangLiMingCi"] = "201名及以后",
    ["UIWorldMap_JuDian_QianWang"] = "前往",
    ["UIWorldMap_JuDian_GuanZhan"] = "观战",
    ["UIWorldMap_JuDian_GongJi"] = "攻击",
    ["UIWorldMap_JuDian_Peoples"] = "人数：",
    ["UIWorldMap_JuDian_Team"] = "阵型",
    ["UIWorldMap_JuDian_Peace"] = "和平",
    ["UIWorldMap_JuDian_Name"] = "城池",
    ["UIWarriorQuality_1"] = "白",
    ["UIWarriorQuality_2"] = "三流",
    ["UIWarriorQuality_3"] = "二流",
    ["UIWarriorQuality_4"] = "成名",
    ["UIWarriorQuality_5"] = "一流",
    ["UIWarriorQuality_6"] = "传奇",
    ["UIWarriorQuality_7"] = "无双",
    ["UIWarriorQuality_8"] = "神",
    ["UIStoreLabel"] = "暂未开放，敬请期待！",
    ["UIWarriorPveNumLimit"] = "武将出战数量已达上限！",
    ["UIRewardOK"] = "可领奖",
    ["UIReBornSelectM"] = "材料人数已满，无需继续添加",
    ["UIWarriorZMValueM"] = "招募值不足，无法购买将魂",
    ["UITuFeiNotEnough"] = "突飞令不足",
    ["UITuFeiSuccess"] = "突飞成功",
}


--TODO:修改下面的，统一到上面ChineseConvert里面
ChineseEquipDetail = 
{
    "名称:",
    "部位:",
    "等级:", 
    "攻击:",
    "血量:", 
    "攻速:", 
    "星级:", 
    "星级效果:",
    "20星:", 
    "25星:", 
    "30星:",
    "40星:",
    "50星:",
    "总计效果:",
    "",
    "价格:",
    "描述:",
}
 
ChineseEquip = {
    [8] = "星",
    [9] = "攻击、生命+7%", 
    [10] = "攻击、生命+5%", 
    [11] = "攻击、生命+8%",
    [12] = "攻速+10%",
    [13] = "攻击+16%", 
    [14] = "    攻击总量+%d%%", 
    [15] = "    生命总量+%d%%", 
    [16] = ""
}

ChineseTip = {
    [1] = "军令：%d/%d",
    [2] = "整点恢复一枚军令",
    [3] = "当前铜钱：%d",
    [4] = "通过招财神符可获得大量铜钱",
    [5] = "当前元宝：%d",
    [6] = "总战力：%d",
    [7] = "提升战斗力捷径：",
    [8] = "武将升级、招募、转生",
    [9] = "士兵升级、进阶",
    [10] = "装备冶炼、强化、重铸",
}